#!/bin/bash

# author: rochdi nassah
# created: 2025/09/19

found=0

while read line
do
  if [[ $line == 'source ~/Desktop/rochdi/bin/bashrc' ]]
  then
    found=1
    break
  fi
done < ~/.bashrc

if [ 0 == $found ]
then
  sed -i '1s/^/source ~\/Desktop\/rochdi\/bin\/bashrc\n\n/' ~/.bashrc
  echo injection ok
fi

if [ ! -d ~/Desktop/apk ]
then
  /usr/bin/mkdir ~/Desktop/apk
fi

node_which=$(which node)
npm_which=$(which npm)

if [ 0 == ${#node_which} ] || [ 0 == ${#npm_which} ]
then
  echo NodeJS or npm are missing, downloading...
  cd /tmp &&
  wget https://nodejs.org/dist/v22.20.0/node-v22.20.0-linux-x64.tar.xz &&
  tar --extract --file node-v22.20.0-linux-x64.tar.xz &&
  sudo mv ./node-v22.20.0-linux-x64/bin/* /usr/bin &> /dev/null
  sudo mv ./node-v22.20.0-linux-x64/include/* /usr/include &> /dev/null
  sudo mv ./node-v22.20.0-linux-x64/lib/* /usr/lib &> /dev/null
  echo NodeJS: $(node -v)
  echo npm: $(npm -v)
fi