#!/bin/bash

# author: rochdi nassah
# created: 2025/09/19

found=0

while read line
do
  if [[ $line == 'source ~/Desktop/rochdi/bin/bashrc' ]]
  then
    found=1
    break
  fi
done < ~/.bashrc

if [ 0 == $found ]
then
  sed -i '1s/^/source ~\/Desktop\/rochdi\/bin\/bashrc\n\n/' ~/.bashrc
  echo injection ok
fi

if [ ! -d ~/Desktop/apk ]
then
echo foo
  /usr/bin/mkdir ~/Desktop/apk
fi