#!/bin/bash

# author: rochdi nassah

found=0

while read line
do
  if [[ $line == 'source /opt/rochdi/bin/bashrc' ]]
  then
    found=1
    break
  fi
done < /etc/bash.bashrc

if [ 0 == $found ]
then
  sed -i '1s/^/source \/opt\/rochdi\/bin\/bashrc\n\n/' /etc/bash.bashrc
  echo injection ok
fi

if [ ! -d /opt/apk ]
then
  /usr/bin/mkdir /opt/apk
fi

node_which=$(which node)
npm_which=$(which npm)

if [ 0 == ${#node_which} ] || [ 0 == ${#npm_which} ]
then
  echo NodeJS or npm are missing, downloading...
  cd /tmp &&
  wget https://nodejs.org/dist/v24.13.0/node-v24.13.0-linux-x64.tar.xz &&
  tar --extract --file node-v24.13.0-linux-x64.tar.xz &&
  sudo mv ./node-v24.13.0-linux-x64/bin/* /usr/bin &> /dev/null
  sudo mv ./node-v24.13.0-linux-x64/include/* /usr/include &> /dev/null
  sudo mv ./node-v24.13.0-linux-x64/lib/* /usr/lib &> /dev/null
  echo NodeJS: $(node -v)
  echo npm: $(npm -v)
fi